revocation_list only call isotime on datetime objects
If expires is a str then isinstance six.text_type is false then the following
exception is raised:
AttributeError: 'str' object has no attribute 'strftime'

This change explicitly checks for a datetime object, which is what
timeutils.isotime expects.

Change-Id: I8012f96498fffe5f54e7f1ca08b7beb6fa168f9c
Closes-Bug: #1285871