Fix test_add_int_pkey_to_revocation_event_table for MySQL
test_add_int_pkey_to_revocation_event_table would fail with

 MismatchError: 'INTEGER' != 'INTEGER(11)'

because the mysql dialect produces a different string for the type.

Use isinstance rather than checking the string.

Change-Id: Ib897bbf0424996edb993a09c920648ea8d6812d7