Ensure database options registered for tests
DeprecatedTestCase and DeprecatedOverrideTestCase use options in the
database section, but these options won't be registered unless
keystone.common.sql.initialize() is called.

This caused the python34 tests to fail with

 oslo_config.cfg.NoSuchOptError: no such option: database

bp python3

Closes-Bug: 1474491
Change-Id: Ic6376142e5e14f1b25cc203c5b37751dc0a25981