Update amqp and PyMySQL lower constraints
Newer versions of kombu rely on updated versions of amqp [0]. Keystone's
lower-constraints job is failing consistently across multiple branches
because it's referencing amqp 2.2.2 when we should be relying on a newer
version (5.0.0+).

You can verify this by using `pip3 check` with the lower-constraints tox
environment.

Without this patch, you'll likely see the test_notifications tests fail
with something like:

  ModuleNotFoundError: No module named 'vine.five'

Which spirals into subsequent failures mocking messaging drivers.

This commit also fixes the lower-constraint for PyMySQL.

keystone does not have any lower constraint for PyMySQL so the
latest version 0.10.0 is picked by the job which is failing [1]
In OpenStack, PyMySQL's upper constraint is 0.9.3. Version 0.10.0 is
not tested [2]. Let's add PyMySQL lower constraint also so that we test
lower-constraint job with correct lower version.

Both of these fixes were proposed separate reviews in newer branches,
but due to a circular failure, they're being proposed together. The
amqp fix fails lower-constraints jobs because the PyMySQL issue and vice
versa.

[0] https://github.com/celery/celery/issues/3547
[1]https://zuul.opendev.org/t/openstack/build/3077d96f4fff4b7985cb763d0635d471/log/job-output.txt#621
[2]https://github.com/openstack/requirements/blob/master/upper-constraints.txt#L384

Change-Id: I3834b3b34641c006c70614d5331d292c41f8a346
Closes-Bug: #1888886
(cherry picked from commit c495defc2bd4f2ef5a38d2a9e4d5aac5653fb406)
(cherry picked from commit 12891a039fb1dae7ba22884cf78ad7d1faa8569d)
(cherry picked from commit b7c3458b6f11ade0ce54889ae5f782fbac4a9a2e)
(cherry picked from commit 255b6cdd70db654ce8112cef0b86361c34d9993b)
(cherry picked from commit 3de085b1eb9750cb0d0d25cb468250cf34804eaf)
(cherry picked from commit 300e79e93b9966e988ec92a74bf9b49b71d77d1b)
(cherry picked from commit fb7d54543fd69e046a5136ca4028f4e128b947c2)
(cherry picked from commit 32967a8105efd2a0934ab123eb10f33df7f581c5)