Remove extraneous _validate_claims() arg.
Extraneous env argument to:

  keystone.middleware.auth_token.AuthProtocol._validate_claims()

causes glance failure when keystone auth strategy is enabled:

  File "/opt/stack/keystone/keystone/middleware/auth_token.py", line 309, in _validate_claims
    return self._validate_claims(env, claims, False)
  NameError: global name '\''env'\'' is not defined

Seen when running devstack on Fedora16.

Change-Id: Ia04c14a709e3b332002dc6cddcda56e247821fa5