test_backend_sql work with python34
test_backend_sql was failing on python34 with two different errors.

1. On python3 we need encode unicode into byte before hashing.

...
    token_id_hash = hash_fn(token_id).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

2. Delete one invalid testcase `test_non_ascii_init` since this testcase
is testing SQLAlchemy behavior rather than keystone, this testcase will also fail
on python3.

...
  File "/opt/stack/keystone/keystone/tests/unit/test_backend_sql.py",
  line 871, in test_non_ascii_init
    self.assertRaises(UnicodeDecodeError, FakeTable, col='Я')

3. Update the name of some generic methods since nose will capture the
keyword 'test' from the method and assume it is a testcase if there is.

bp python3
Change-Id: I68a8848ea2672efc206fdab0d29b32685678e3bf