Make opensuse jobs nonvoting
The opensuse images tend to be less stable, and the opensuse nodeset was
moved to openSUSE 15.2 which does not work properly with devstack for
the train and lower branches. Ussuri works for the moment, and Victoria+
have been moved to Ubuntu, so this patch is targeted for stable/train
and prior to disable voting for opensuse-based jobs.

To fix the gate, patch also pulls in this backport:

Update amqp lower constraint

Newer versions of kombu rely on updated versions of amqp [0]. Keystone's
lower-constraints job is failing consistently across multiple branches
because it's referencing amqp 2.2.2 when we should be relying on a newer
version (5.0.0+).

You can verify this by using `pip3 check` with the lower-constraints tox
environment.

Without this patch, you'll likely see the test_notifications tests fail
with something like:

  ModuleNotFoundError: No module named 'vine.five'

Which spirals into subsequent failures mocking messaging drivers.

[0] https://github.com/celery/celery/issues/3547

(cherry picked from commit c495defc2bd4f2ef5a38d2a9e4d5aac5653fb406)
(cherry picked from commit 12891a039fb1dae7ba22884cf78ad7d1faa8569d)
(cherry picked from commit d435a915160a9876b58f2a04696d9430790e5cdc)

Change-Id: I2895300556b83e943ce5e5fd72e4b86317a306a9