Fixes for Active Directory
The LDAP Identity backend was not properly using the
user_enabled_default option as a string. This caused
operations to fail with

 TypeError: unsupported operand type(s) for &: 'str' and 'int'

Also, fetching users using the LDAP Identity backend would fail with

 KeyError: 'enabled'

from _ldap_res_to_model when user_enabled_mask is not 0.

Closes-Bug: #1210175
(cherry picked from commit 68f38a65c60485c34474e490d649b328421e10f5)
(cherry picked from commit 116897786dbb8473154ec85a01b019af8106a1f4)
(cherry picked from commit 54178b735dea4dfee4578caa95cb3ae704afef07)
(cherry picked from commit 87ababb38506a1a51b9e38fc343dd3b46c828a80)
(cherry picked from commit 781c65b72b78bd1e2b1d93db029d6b0c6fbc2050)

Change-Id: Ic01aa505d867c1de30e2a1ed7c79ff1478e213ef