Fix mysql checkout handler AttributeError
If the mysql_on_checkout handler encountered an error due to
disconnect, it would fail with an AttributeError,

 AttributeError: 'module' object has no attribute 'warn'

This is because it used the logging module where the LOG logger
should have been used.

Change-Id: Iae8a9bd4aeee6e35508059c20b92d70c36232963
Closes-Bug: #1234873